### ISSUE TITLE
HTTPS工作原理

### ISSUE THREAD

**Issue by kmokidd** [CatTail/cattail.github.io#1]
感谢这篇原理解释的文章，只是文中有一段话不是太明白：初始当前状态（Current State）没有指定加密，压缩和MAC算法，因而在完成TLS Handshaking Protocols一系列动作之前，客户端和服务端的数据都是明文传输的；当TLS完成握手过程后，客户端和服务端确定了加密，压缩和MAC算法及其参数，数据（Record）会通过指定算法处理。
1. TLS Record Protocol 有 Handshake Protocol 子协议，这个子协议和 TLS Handshake Protocol 是不一样的协议吗？
2. ”在完成 TLS Handshaking Protocols 一系列动作之前“，这里似乎讲得一直都是 TLS Record Protocol，这两个协议是有先后的完成顺序吗？
3. 客户端和服务器能够明文传输的就是加密、压缩和MAC算法及其参数吗？

感谢您的解答。

**Comment by CatTail** [comment]
1. TLS协议由TLS Record Protocol和TLS Handshake Protocol组成，文中说的Handshake Protocol就是TLS Handshake Protocol。
2. Handshake Protocol和Record Protocol不是先后关系，而是层次关系。
3. 两端在握手过程中除了premaster secret，其它参数都是明文传输的。

**Comment by kmokidd** [comment]
感谢您的解答。

也就是说， TLS 协议有两个部分组成，其中 Handshake 是运行在 Record Protocol 上的子协议，而 Record Protocol 除了有 Handshake 这个子协议之外，还有另外三个子协议，这样？

**Comment by CatTail** [comment]
TLS 协议有两个部分组成，其中 Handshake 是运行在 Record Protocol 上的子协议，而在 Record Protocol 上除了可以运行 Handshake 这个协议之外，还有运行其它协议。

Record Protocol和Handshake Protocol并没有父子协议这样的关系。建议看一下[spec](https://tools.ietf.org/html/rfc5246)
