### ISSUE TITLE
知识处理体系

### ISSUE THREAD

**Issue by creamidea** [CatTail/cattail.github.io#3]
前段时间也在整理自己的思路：如何对知识进行处理。感觉和Po主的思路大致相同 :P 
但是还没有Po主的执行能力。

我的思路是这个样子的：想模仿GTD的思路，有一个 Inbox 专门用来收集不同的知识，之后进行整理，执行和回顾。最后Repeat。

不过关于很碎片的知识（没有过什么概括性）不知道如何整理，比如各个激活码之类的这些，不知道Po主食怎么处理的？

**Comment by CatTail** [comment]
对于激活码这类的 ”数据“，可能并不能和其他需要我们去消化理解的知识统一处理，可能是你举的例子不太合适，一般非知识内容我会放在单独的称为 ”备忘录“ 的地方。

知识处理体系仅处理 ”知识“，而并不想做到收集处理我们看到的所有信息。

**Comment by creamidea** [comment]
你这么说也是。这种不是用来记忆的知识还是放入备忘录中保存较好。
